spring:
  application:
    name: information-modal-api
  main:
    banner-mode: log
  datasource:
    url: jdbc:mariadb://${INFORMATION_MODAL_DB_HOST:-localhost}:${INFORMATION_MODAL_DB_PORT:-3306}/${INFORMATION_MODAL_DB_NAME:-InformationModalDB}?useUnicode=yes&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${INFORMATION_MODAL_DB_USERNAME:-root}
    password: ${INFORMATION_MODAL_DB_PASSWORD:-root}

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: ${INFORMATION_MODAL_PORT:-8080}
  servlet:
    context-path: /informationModal